const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
app.setPath('userData', path.join(os.tmpdir(), 'pokemux-market-refresh-test-' + process.pid));
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, webPreferences: { backgroundThrottling: false } });
  try {
    await win.loadURL('data:text/html,<button id="marketBtn">Market</button>');
    await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname, '../src/domain/pokemon-state.js'), 'utf8'));
    await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname, '../src/domain/global-market.js'), 'utf8'));
    await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname, '../src/renderer/global-market.js'), 'utf8'));
    const result = await win.webContents.executeJavaScript(`(async () => {
      const check = (ok, message) => { if (!ok) throw Error(message); };
      const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
      let listingLevel = 20, listingCount = 12, quoteEnabled = false, pageWait = null;
      let tick, active = false, version = 1, fail = '', held = null, reads = [];
      let ivEnabled = true, ivCalls = [], ivShown = null, ivWaiting = null;
      window.setInterval = (callback, ms) => { check(ms === 60000, 'interval'); tick = callback; active = true; return 1; };
      window.clearInterval = () => { active = false; };
      window.PokeMuxMarketAlerts = { normalize: x => x, create: () => ({ setRules() {}, state() {}, check() {}, stop() {} }) };
      const read = async (_account, script) => {
        const query = JSON.parse(script.match(/\\}\\)\\((\\{[^\\n]*?\\}),/)[1]); reads.push(query);
        if (pageWait && query.browse === 'pokemon' && query.page === '2') await new Promise(resolve => pageWait.push(resolve));
        if (held) await new Promise(resolve => held.push(resolve));
        if (fail) return { ok: false, reason: fail };
        const listings = Array.from({ length: listingCount }, (_, i) => ({ id: 'listing' + i, kind: 'pokemon', name: 'Abra', speciesId: 63, price: version * 100 + i, currency: 'GOLD', ivTotal: 160, quality: 1.5, level: listingLevel, stats: { hp: 100, atk: 40, def: 30, spAtk: 80, spDef: 60, speed: 50 }, at: new Date().toISOString() }));
        const responseListings = quoteEnabled && query.category === 'All' ? [...listings, {id:'quote',kind:'diamonds',price:10000,currency:'GOLD',quantity:1}] : listings;
        return { ok: true, data: { cid: 'c1', name: 'Tester', listings:responseListings, total: 36, pages: 3, ownedReady: true, owned: [{ id: 'pokemon:owned', kind: 'pokemon', speciesId: 63, name: 'Abra', level: 20, ivTotal: 160, quality: 1.5, stats: { hp: 100, atk: 40, def: 30, spAtk: 80, spDef: 60, speed: 50 } }], catalog: { items: [{ kind: 'item', refId: 9, name: 'Potion' }] }, species: [{ speciesId: 63, name: 'Abra', total: 36 }], alertCatalog: [{ kind: 'pokemon', speciesId: 63, name: 'Abra' }] } };
      };
      const ui = PokeMuxMarketUI.mount({ marketSnapshotOptions: {enabled:false}, marketReaderOptions: {interval:0,ttl:0}, load: () => '', save() {}, language: () => 'pt', sprite: () => '', preferred: () => 0, accounts: async () => [{ focused: true, live: true, off: false, name: 'Tester' }], read, rememberFocus() {}, isIvEnabled: () => ivEnabled,
        calculateIv: async (account, pokemon, cid) => { ivCalls.push({ account, pokemon, cid }); if (ivWaiting) return new Promise(resolve => ivWaiting.push({ resolve, pokemon })); return { nome: pokemon.name, id: pokemon.id }; },
        showIv(account, result, point) { ivShown = { account, result, point }; }, hideIv() { ivShown = null; } });
      const el = selector => document.querySelector(selector);
      await ui.open(); await pause(30);
      el('[data-category="Pokemon"]').click(); await pause(30);
      check(el('[data-listing="listing0"]') && !el('[data-species]'), 'Pokemon opens all listings directly');
      check(!reads.some(x => x.browse === 'species'), 'species landing query removed');
      check(el('#mkSearch').placeholder === 'Buscar Pokémon', 'Pokemon name search at top');
      const firstPokemon = el('[data-listing="listing0"]'), secondPokemon = el('[data-listing="listing1"]');
      firstPokemon.dispatchEvent(new MouseEvent('mouseover', { bubbles: true, clientX: 120, clientY: 130 })); await pause(30);
      check(ivShown.result.id === 'listing0' && ivCalls[0].pokemon.stats.spAtk === 80 && ivCalls[0].cid === 'c1', 'IV receives exact listing stats and session');
      const ivCount = ivCalls.length;
      firstPokemon.dispatchEvent(new MouseEvent('mousemove', { bubbles: true, clientX: 140, clientY: 150 }));
      check(ivCalls.length === ivCount && ivShown.point.x === 140, 'IV follows cursor without recalculation');
      firstPokemon.dispatchEvent(new MouseEvent('mouseout', { bubbles: true, relatedTarget: secondPokemon }));
      ivWaiting = [];
      firstPokemon.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
      firstPokemon.dispatchEvent(new MouseEvent('mouseout', { bubbles: true, relatedTarget: secondPokemon }));
      secondPokemon.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
      const pendingIv = ivWaiting.splice(0); ivWaiting = null;
      pendingIv[1].resolve({ id: 'listing1' }); await pause(10);
      pendingIv[0].resolve({ id: 'listing0' }); await pause(10);
      check(ivShown.result.id === 'listing1', 'late IV from another listing rejected');
      secondPokemon.dispatchEvent(new MouseEvent('mouseout', { bubbles: true }));
      ivEnabled = false; firstPokemon.dispatchEvent(new MouseEvent('mouseover', { bubbles: true })); await pause(10);
      check(ivShown === null, 'IV OFF respected'); ivEnabled = true;
      el('#mkSearch').value = 'Abra'; el('#mkSearch').dispatchEvent(new Event('input', { bubbles: true })); await pause(800);
      el('#mkIvMin').value = '150'; el('#mkIvMin').dispatchEvent(new Event('input', { bubbles: true })); await pause(800);
      el('#mkSort').value = 'price-asc'; el('#mkSort').dispatchEvent(new Event('change')); await pause(800);
      el('[data-page="2"]').click(); await pause(30);
      el('[data-listing="listing0"]').click();
      el('#mkIvMin').focus(); el('#mkResults').style.height = '150px'; el('#mkResults').style.overflow = 'auto'; el('#mkResults').scrollTop = 80;
      const scroll = el('#mkResults').scrollTop;
      reads = []; version = 2; tick(); await pause(30);
      const query = reads.find(x => x.browse === 'pokemon');
      check(query.page === '2' && query.ivMin === '150' && query.sort === 'price-asc' && query.q === 'Abra' && !query.speciesId, 'query state preserved');
      check(el('#mkPage').value === '2' && el('#mkIvMin').value === '150', 'page and filters preserved');
      check(document.activeElement.id === 'mkIvMin', 'focus preserved');
      check(el('#mkResults').scrollTop === scroll, 'scroll preserved');
      check(el('[data-listing="listing0"]').classList.contains('selected'), 'selected listing preserved');
      check(!el('.mk-details') && el('[data-listing="listing0"]').textContent.includes('200'), 'listing data refreshed without side panel');
      const previous = el('#mkResults').innerHTML;
      fail = 'network'; tick(); await pause(30);
      check(el('#mkResults').innerHTML === previous, 'failed refresh keeps visible results');
      fail = ''; held = []; reads = []; tick(); await pause(10); const count = reads.length; tick(); await pause(10);
      check(reads.length === count, 'overlapping automatic refresh skipped');
      ui.close(); held.splice(0).forEach(resolve => resolve()); held = null; await pause(30);
      check(!active && !el('#pmMarket').classList.contains('show'), 'closing stops refresh');
      await ui.open(); await pause(30);
      reads = []; el('[data-tab="compare"]').click(); await pause(30);
      check(el('[data-owned="pokemon:owned"]'), 'bag Pokemon available');
      check(el('[data-owned="pokemon:owned"]').textContent.includes('Abra') && el('[data-owned="pokemon:owned"]').textContent.includes('IV 160'), 'inventory row identifies the exact specimen');
      check(!el('.mk-bag-slot.empty'), 'inventory has no decorative empty slots');
      const beforeSearch = reads.length;
      el('#mkOwnSearch').value = 'missing'; el('#mkOwnSearch').dispatchEvent(new Event('input', {bubbles:true}));
      check(!el('[data-owned]'), 'inventory search hides unmatched specimens');
      el('#mkOwnSearch').value = 'Abra'; el('#mkOwnSearch').dispatchEvent(new Event('input', {bubbles:true}));
      check(el('[data-owned="pokemon:owned"]') && reads.length === beforeSearch, 'inventory search is local and retains the exact specimen ID');
      el('[data-owned="pokemon:owned"]').click(); await pause(30);
      check(el('.mk-own-info .mk-stats').textContent.includes('80'), 'bag attributes displayed');
      check(el('.mk-sale-recommendation').textContent.includes('206'), 'median selling recommendation shown');
      const comparisonReads = reads.filter(x => x.browse === 'pokemon');
      check(comparisonReads.length === 3 && comparisonReads.every(x => x.speciesId === '63' && x.ivMin === '150' && x.lvMin === '10' && x.qMin === '1.4'), 'comparison sends specimen tolerances to the server');
      version = 3; tick(); await pause(30);
      check(el('.mk-sale-recommendation').textContent.includes('306'), 'selling recommendation refreshed');
      listingLevel = 494; tick(); await pause(30);
      check(!el('.mk-sale-recommendation').textContent.includes('Preço de referência da espécie'), 'different levels do not automatically become a selling reference');
      check(el('.mk-own-info').textContent.includes('Sem anúncios semelhantes'), 'no similar level or rarity warning visible');
      el('[data-widen]').click(); await pause(30);
      check(el('.mk-sale-recommendation').textContent.includes('Preço de referência da espécie'), 'species reference requires explicit widening');
      listingCount = 0; tick(); await pause(30);
      check(el('.mk-sale-recommendation').textContent.includes('Nenhum resultado encontrado'), 'no species listing is distinct from incomplete bag');
      el('[data-tab="alerts"]').click(); await pause(30);
      el('#mkAlertSearch').value = 'Pot'; el('#mkAlertSearch').dispatchEvent(new Event('input', { bubbles: true }));
      el('[name="priceMax"]').value = '123'; el('[name="voice"]').checked = false; el('#mkAlertSearch').focus();
      tick(); await pause(30);
      check(el('#mkAlertSearch').value === 'Pot' && el('[name="priceMax"]').value === '123' && !el('[name="voice"]').checked, 'alert draft preserved');
      check(document.activeElement.id === 'mkAlertSearch', 'draft focus preserved');
      ui.close();
      return 'ok market-refresh: IV stats, hover, cursor, stale responses, toggle, no side panel, comparison, 60s refresh, filters, focus, failures and close';
    })()`);
    console.log(result); win.destroy(); app.exit(0);
  } catch (error) { console.error(error); win.destroy(); app.exit(1); }
});
