const assert = require('node:assert/strict');
const M = require('../src/domain/global-market');
(async () => {
  let now = 100000, version = 1, calls = 0, release, failed = false, saved;
  const read = async (_account,script) => {
    calls++;
    const q = JSON.parse(script.match(/\}\)\((\{[^\n]*?\}),/)[1]);
    if (q.browse && q.page === '2' && release) await new Promise(resolve=>release.push(resolve));
    if (q.browse && q.page === '2' && failed) return {ok:false,reason:'limited'};
    const base = version === 1 ? 0 : 1;
    const start = q.page === '2' ? 12 : 0;
    const listings = q.browse ? Array.from({length:12},(_,i)=>({id:String(start+i+base),kind:'pokemon',speciesId:63,name:'Abra',ivTotal:180,level:20,quality:1.5,price:(start+i+base+1)*10000,currency:'GOLD'})) : [{id:'quote',kind:'diamonds',quantity:1,price:10000,currency:'GOLD'}];
    return {ok:true,data:{cid:'c1',listings,total:24,pages:2}};
  };
  let cleared = 0; read.clearPages = ()=>cleared++;
  const store = M.createSnapshotCache(read,{now:()=>now,save:value=>{saved=value;}});
  const first = await store.ensure(0,'c1');
  assert.equal(first.snapshot.listings.length,24);
  assert.equal(calls,3);
  assert.equal(store.get(1,'c1'),null,'accounts isolated');
  assert.equal(store.get(0,'c2'),null,'characters isolated');
  const initial = store.get(0,'c1');
  const sorted = M.snapshotPage(initial,{sort:'price-asc',page:2});
  assert.equal(sorted.data.listings[0].id,'12');
  assert.equal(calls,3,'local sort and pagination make no requests');
  assert.equal(M.snapshotPage(initial,{ivMin:190}).data.total,0);
  now+=60001; version=2; release=[];
  const job = store.ensure(0,'c1',true), joined=store.ensure(0,'c1',true);
  assert.equal(job,joined,'opening and background refresh share the same scan');
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(store.get(0,'c1'),initial,'no per-page publication');
  const callbacks=release; release=null; callbacks.forEach(resolve=>resolve()); await job;
  assert.equal(store.get(0,'c1').listings.some(x=>x.id==='0'),false,'removed listing deleted');
  assert.equal(store.get(0,'c1').listings.some(x=>x.id==='24'),true,'new listing added');
  assert.equal(cleared,1,'reconciliation bypasses old cached pages');
  const completed=store.get(0,'c1');
  now+=60001; failed=true;
  assert.equal((await store.ensure(0,'c1',true)).reason,'limited');
  assert.equal(store.get(0,'c1'),completed,'failed scan preserves complete previous snapshot');
  const restored=M.createSnapshotCache(read,{initial:saved,now:()=>now});
  assert.equal(restored.get(0,'c1').listings.length,24,'local cache restored after app restart');
  assert.equal(restored.get(0,'c2'),null);
  store.stop();
  console.log('ok market-snapshot: warm cache, local filters, atomic replacement, removals, failures, persistence and isolation');
})().catch(error=>{console.error(error);process.exitCode=1;});
