const assert=require('node:assert/strict');
const M=require('../src/domain/global-market');
(async()=>{
  const gold=Array.from({length:124},(_,i)=>({id:'g'+i,kind:'pokemon',name:'Abra',speciesId:63,ivTotal:180,currency:'GOLD',price:400000+i*100000}));
  const diamonds=Array.from({length:605},(_,i)=>({id:'d'+i,kind:'pokemon',name:'Abra',speciesId:63,ivTotal:180,currency:'DIAMONDS',price:3+i}));
  const calls=[];
  let fail=false,changed=false;
  const read=async script=>{
    const q=JSON.parse(script.match(/\}\)\((\{[^\n]*?\}),/)[1]);calls.push(q);
    if(fail)return {ok:false,reason:'limited'};
    let list=q.currency==='GOLD'?gold:diamonds;
    if(q.sort==='price-desc')list=[...list].reverse();
    const offset=(Number(q.page)-1)*12;
    return {ok:true,data:{cid:changed?'c2':'c1',listings:list.slice(offset,offset+12),total:list.length,pages:Math.ceil(list.length/12)}};
  };
  const rate=2700000,options={sort:'price-asc',ivMin:175,page:1};
  let result=await M.readPricePage(read,options,'c1',[],rate);
  assert.equal(result.ok,true);
  assert.equal(calls.length,2,'729 listings need only two requests for the first page');
  assert.equal(result.data.total,729);assert.equal(result.data.pages,61);
  assert.deepEqual(result.data.listings.map(x=>x.id),gold.slice(0,12).map(x=>x.id));
  assert.ok(calls.every(q=>q.ivMin==='175'&&q.sort==='price-asc'&&q.currency));
  const original=result.book;
  result=await M.readPricePage(read,{...options,page:2},'c1',[],rate,result.book);
  assert.equal(calls.length,3,'next page fetches only the exhausted currency frontier');
  assert.equal(original.listings.length,12,'previous cursor is immutable');
  const full=M.sortPrices([...gold,...diamonds],'price-asc',rate);
  result=await M.readPricePage(read,{...options,page:12},'c1',[],rate,result.book);
  assert.deepEqual(result.data.listings.map(x=>x.id),full.slice(132,144).map(x=>x.id),'interleaved currencies match exhaustive conversion');
  const count=calls.length;
  const back=await M.readPricePage(read,options,'c1',[],rate,result.book);
  assert.equal(calls.length,count,'return to an already merged page uses no requests');
  assert.equal(back.data.listings[0].id,'g0');
  const descending=await M.readPricePage(read,{...options,sort:'price-desc'},'c1',[],rate);
  assert.deepEqual(descending.data.listings.map(x=>x.id),M.sortPrices([...gold,...diamonds],'price-desc',rate).slice(0,12).map(x=>x.id));
  fail=true;
  assert.equal((await M.readPricePage(read,{...options,page:61},'c1',[],rate,result.book)).reason,'limited');
  assert.equal(result.book.listings.length,144,'failure cannot mutate the usable cursor');
  fail=false;changed=true;
  assert.equal((await M.readPricePage(read,options,'c1',[],rate)).reason,'changed');
  const ignored=await M.readPricePage(async()=>({ok:true,data:{cid:'c1',listings:[diamonds[0]],total:1,pages:1}}),options,'c1',[],rate);
  assert.equal(ignored.reason,'server','ignored currency filter never produces a false global ranking');
  console.log('ok market-price-page: two requests, exact mixed-currency merge, IV filters, pagination, descending, failure and session');
})().catch(error=>{console.error(error);process.exitCode=1;});
