'use strict';
const assert=require('node:assert/strict');
const S=require('../src/renderer/summary.js');
assert.equal(S.duration(500,100,1200),6000);
assert.equal(S.duration(0,100,1200),0);
assert.equal(S.duration(500,0,1200),null);
assert.equal(S.duration(500,100,300),null);
assert.equal(S.duration(undefined,100,1200),null);
assert.equal(S.duration(1,100,1200,true),Infinity);
assert.equal(S.health({st:'down',farm:{hunting:true}}).status,'down');
assert.equal(S.health({st:'on'}).status,'wait','missing farm state is not assumed active');
assert.equal(S.health({st:'on',farm:{hunting:false}}).status,'idle');
assert.equal(S.health({st:'on',farm:{hunting:true,lastCombatT:1000}},200000).status,'stalled');
assert.equal(S.health({st:'on',farm:{hunting:true,lastCombatT:190000}},200000).status,'hunting');
assert.deepEqual(S.health({st:'on',balls:0,pots:0}).issues,[],'missing inventory snapshots do not trigger false supply warnings');
assert.deepEqual(S.health({st:'on',balls:0,hasBalls:true,pots:0,hasInv:true,aPots:1,lead:{hp:0,hm:100}}).issues,['faint','emptyBalls','emptyPotions']);
assert.deepEqual(S.health({st:'on',balls:0,hasBalls:true,infiniteBalls:true}).issues,[]);
assert.equal(S.important({iv:159,q:1.69}),false);
assert.equal(S.important({iv:160,q:1}),true);
assert.equal(S.important({iv:80,q:1.7}),true);
assert.equal(S.important({iv:80,q:1,sh:true}),true);
assert.equal(S.important(null),false);
const input=[{n:'ordinary',t:300,iv:50},{n:'highIV',t:200,iv:160},{n:'shiny',t:100,sh:true}];
assert.deepEqual(S.prioritize(input).map(x=>x.n),['shiny','highIV','ordinary']);
assert.equal(input[0].n,'ordinary','ordering never mutates history');
assert.deepEqual(S.prioritize([null]),[]);
console.log('Resumo: consumo medido, bolas infinitas, problemas, dados ausentes e prioridade de capturas aprovados.');
